import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from 'next/headers'
import { cookieToInitialState } from 'wagmi'
import Web3ModalProvider from '@/components/context/web3modal'
import { config } from "@/config/chain";
import "./globals.css";
import {Toaster} from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Git ID",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const initialState = cookieToInitialState(config, headers().get('cookie'))

    return (
        <html lang="en">
                <body className={inter.className}>
                    <Web3ModalProvider initialState={initialState}>
                        {children}
                        <Toaster position="top-center" richColors />
                    </Web3ModalProvider>
                </body>
        </html>
    );
}
